### ISSUE TITLE
`gem "phlex"` breaks `bundle exec sitepress console`

### ISSUE THREAD

**Issue by joemasilotti** [sitepress/sitepress#14]
Running `bundle exec sitepress console` with `gem "phlex"` in the Gemfile raises the following exception:

```
bundler: failed to load command: sitepress (/Users/joemasilotti/.rbenv/versions/2.7.1/bin/sitepress)
SyntaxError: /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/phlex-0.5.3/lib/phlex/compiler/formatter.rb:69: syntax error, unexpected (...
			def text(value, ...)
			                ^~~
/Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/phlex-0.5.3/lib/phlex/compiler/formatter.rb:91: syntax error, unexpected `end', expecting end-of-input
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:30:in `require'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:30:in `require'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `cget'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `each'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `ls'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `each'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:296:in `block in eager_load_all'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `each'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `eager_load_all'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.4/lib/rails/application/finisher.rb:74:in `block in <module:Finisher>'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `instance_exec'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.4/lib/rails/initializable.rb:32:in `run'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.4/lib/rails/initializable.rb:61:in `block in run_initializers'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `call'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.4/lib/rails/initializable.rb:60:in `run_initializers'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.4/lib/rails/application.rb:372:in `initialize!'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.4/lib/rails/railtie.rb:226:in `public_send'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-7.0.4/lib/rails/railtie.rb:226:in `method_missing'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sitepress-cli-3.2.0/lib/sitepress/cli.rb:113:in `initialize!'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sitepress-cli-3.2.0/lib/sitepress/cli.rb:64:in `console'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
  /Users/joemasilotti/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sitepress-3.2.0/exe/sitepress:5:in `<top (required)>'
  /Users/joemasilotti/.rbenv/versions/2.7.1/bin/sitepress:23:in `load'
  /Users/joemasilotti/.rbenv/versions/2.7.1/bin/sitepress:23:in `<top (required)>'
```

Removing the item from the Gemfile and bundling removes the error.

**Comment by joemasilotti** [comment]
I'm using:

```
➜  sitepress git:(main) ✗ bundle exec sitepress version
3.2.0

➜  sitepress git:(main) ✗ ruby -v
ruby 2.7.1
```

Upgrading to Ruby 3.1.2 fixes the issue.
