### ISSUE TITLE
[Question] Why does Sitepress depend on Active Record and Active Job?

### ISSUE THREAD

**Issue by joemasilotti** [sitepress/sitepress#46]
I'm creating a bare-minimum Rails app to embed Sitepress into. But I had to re-enable Active Record and Active Job to run the installer.

**Edit**: Some more context, I don't have a need for a database. But including Active Record requires there be a database configuration file with a valid database configured.

With the following `config/application.rb`:

```rb
require_relative "boot"

require "rails"

require "active_model/railtie"
require "action_controller/railtie"
require "action_view/railtie"

Bundler.require(*Rails.groups)
```

Output:
<details>
```
➜  sitepress git:(main) ✗ bin/rails generate sitepress:install
/Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/railtie/configuration.rb:109:in `method_missing': undefined method `active_record' for #<Rails::Application::Configuration:0x000000000028f0> (NoMethodError)
	from /Users/joemasilotti/workspace/projects/masilotti.com/sitepress/config/environments/development.rb:46:in `block in <main>'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/railtie.rb:257:in `instance_eval'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/railtie.rb:257:in `configure'
	from /Users/joemasilotti/workspace/projects/masilotti.com/sitepress/config/environments/development.rb:3:in `<main>'
	from <internal:/Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/engine.rb:561:in `block (2 levels) in <class:Engine>'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/engine.rb:560:in `each'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/engine.rb:560:in `block in <class:Engine>'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:32:in `run'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:50:in `each'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:415:in `call'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/application.rb:423:in `initialize!'
	from /Users/joemasilotti/workspace/projects/masilotti.com/sitepress/config/environment.rb:5:in `<main>'
	from <internal:/Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/application.rb:399:in `require_environment!'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command/actions.rb:20:in `boot_application!'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command/base.rb:178:in `invoke_command'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command/base.rb:73:in `perform'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:71:in `block in invoke'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:149:in `with_argv'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:69:in `invoke'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands.rb:18:in `<main>'
	from <internal:/Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```
</details>

And then adding in Active Record to `config/application.rb`:

```rb
require_relative "boot"

require "rails"

require "active_model/railtie"
require "active_record/railtie"
require "action_controller/railtie"
require "action_view/railtie"

Bundler.require(*Rails.groups)
```

Output:
<details>
```
➜  sitepress git:(main) ✗ bin/rails generate sitepress:install
/Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/railtie/configuration.rb:109:in `method_missing': undefined method `active_job' for #<Rails::Application::Configuration:0x00000000002918> (NoMethodError)
	from /Users/joemasilotti/workspace/projects/masilotti.com/sitepress/config/environments/development.rb:52:in `block in <main>'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/railtie.rb:257:in `instance_eval'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/railtie.rb:257:in `configure'
	from /Users/joemasilotti/workspace/projects/masilotti.com/sitepress/config/environments/development.rb:3:in `<main>'
	from <internal:/Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/engine.rb:561:in `block (2 levels) in <class:Engine>'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/engine.rb:560:in `each'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/engine.rb:560:in `block in <class:Engine>'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:32:in `run'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:50:in `each'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:415:in `call'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/application.rb:423:in `initialize!'
	from /Users/joemasilotti/workspace/projects/masilotti.com/sitepress/config/environment.rb:5:in `<main>'
	from <internal:/Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/application.rb:399:in `require_environment!'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command/actions.rb:20:in `boot_application!'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command/base.rb:178:in `invoke_command'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command/base.rb:73:in `perform'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:71:in `block in invoke'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:149:in `with_argv'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/command.rb:69:in `invoke'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.1.1/lib/rails/commands.rb:18:in `<main>'
	from <internal:/Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from <internal:/Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
	from /Users/joemasilotti/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `<main>'
```
</details>

**Comment by bradgessler** [comment]
It's probably the phlex-rails dependency. Try removing it from Gemfiles and it should work.

I opened an issue at https://github.com/phlex-ruby/phlex-rails/pull/110, which has been merged but not released.

Also older versions of markdown-rails had this problem, so I relaxed the dependency to only include rallies.

Give that a go and close this issue if the dependencies are solved. If not run `bundle viz` and post the graph here so I can check all the dependencies.

**Comment by joemasilotti** [comment]
![gem_graph](https://github.com/sitepress/sitepress/assets/2092156/8621bcf4-b5eb-42f3-a18b-2ecef234e45b)

**Comment by bradgessler** [comment]
It looks like markdown-rails is creating that dependency. I fixed this about a month ago with https://github.com/sitepress/markdown-rails/commit/affdd794a7de4a2b10a7e8971f12ca9bbc3b3cff. If you update to the latest version of markdown-rails this should fix the issue. If that doesn't work please re-open this issue!
